### PR TITLE
Gradle artifactory plugin does not allow to publish the same file in …

### PR DESCRIPTION
**Pull request by epeee**
…2 different publications

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thanks for this pull request @epeee.
Can you pleas sign [JFrog's CLA](https://www.jfrog.com/confluence/display/OSS/How+to+Contribute) so that we can merge your code?

**Comment by epeee** [comment]
I signed JFrog's CLA.

**Comment by eyalbe4** [comment]
@epeee, Gradle Artifactory Plugin 4.4.4 has just been released and includes this 
Thank you for this pull request.

**Comment by epeee** [comment]
@eyalbe4 thx, we are already using it.

**Pull request merged**
